# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.0/filebeat-module-zeek.html

- module: zeek
  # All logs
  connection:
    enabled: true
  dns:
    enabled: true
    var.paths:
      - /pcap/*dns*.log
  http:
    enabled: true
    var.paths:
      - /pcap/*http*.log
  files:
    enabled: true
    var.paths:
      - /pcap/*files*.log
  ssl:
    enabled: true
    var.paths:
      - /pcap/*ssl*.log
  notice:
    enabled: true
    var.paths:
      - /pcap/*notice*.log